=== ragePowered/epam-training-rogovets/trunk/src/main/java/Project3/OldCard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="oldCardList">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="oldCard" type="oldCardType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="oldCardType">
        <xs:sequence>
            <xs:element name="theme" type="xs:string"/>
            <xs:element name="type" type="cardType"/>
            <xs:element name="cuntry" type="country"/>
            <xs:element name="year" type="year"/>
            <xs:element name="author" type="authorList"/>
            <xs:element name="valuable" type="valueType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="cardType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Вітання"/>
            <xs:enumeration value="Реклама"/>
            <xs:enumeration value="Звичайна"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="country">
        <xs:restriction base="xs:string">
            <xs:enumeration value="US"/>
            <xs:enumeration value="UA"/>
            <xs:enumeration value="EN"/>
            <xs:enumeration value="FR"/>
            <xs:enumeration value="TU"/>
            <xs:enumeration value="IT"/>
            <xs:enumeration value="BR"/>
            <xs:enumeration value="BL"/>
            <xs:enumeration value="CH"/>
            <xs:enumeration value="JP"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="valueType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Історична ціність"/>
            <xs:enumeration value="Колеційна цінність"/>
            <xs:enumeration value="Тематична цінність"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="authorList">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="year">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2014"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== ragePowered/epam-training-rogovets/trunk/src/main/java/Project3/instance.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<oldCardList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OldCard.xsd">
    <oldCard>
        <theme>Корови</theme>
        <type>Вітання</type>
        <cuntry>FR</cuntry>
        <year>1964</year>
        <author>Я.Кириченко О.Безвіконний</author>
        <valuable>Колеційна цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Ведмеді</theme>
        <type>Реклама</type>
        <cuntry>JP</cuntry>
        <year>1946</year>
        <author>І.Пастушенко Н.Кольчіба Т.Дємідова</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Дюни</theme>
        <type>Вітання</type>
        <cuntry>UA</cuntry>
        <year>1924</year>
        <author>Л.Дорнер</author>
        <valuable>Історична ціність</valuable>
    </oldCard>
    <oldCard>
        <theme>Дисней</theme>
        <type>Вітання</type>
        <cuntry>IT</cuntry>
        <year>1968</year>
        <author>С.Вересоцький С.Давиденко Ю.Білановська</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Різдво</theme>
        <type>Реклама</type>
        <cuntry>UA</cuntry>
        <year>1988</year>
        <author>М.Крищанович В.Мазаєва П.Петрушко</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Мініатюри</theme>
        <type>Реклама</type>
        <cuntry>UA</cuntry>
        <year>1991</year>
        <author>В.Мазаєва О.Безвіконний А.Роговець</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Веслувальні човни</theme>
        <type>Звичайна</type>
        <cuntry>UA</cuntry>
        <year>1946</year>
        <author>О.Кухаренко А.Ярова</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Відомі особи</theme>
        <type>Вітання</type>
        <cuntry>BL</cuntry>
        <year>2005</year>
        <author>А.Гранатова А.Роговець</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Рись</theme>
        <type>Реклама</type>
        <cuntry>BR</cuntry>
        <year>1988</year>
        <author>М.Крищанович Ю.Білановська</author>
        <valuable>Тематична цінність</valuable>
    </oldCard>
    <oldCard>
        <theme>Статуї</theme>
        <type>Вітання</type>
        <cuntry>CH</cuntry>
        <year>1934</year>
        <author>С.Давиденко</author>
        <valuable>Колеційна цінність</valuable>
    </oldCard>
</oldCardList>
